#!/usr/bin/env sh

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
# این اسکریپت استاندارد Gradle Wrapper است. فایل باینری gradle-wrapper.jar
# به دلیل نبود دسترسی اینترنت در محیط تولید این پروژه اضافه نشده است.
# پیش از اولین اجرا، در Android Studio پروژه را باز کنید؛ IDE به‌طور خودکار
# gradle-wrapper.jar را دانلود و بازسازی می‌کند، یا دستور زیر را اجرا کنید:
#   gradle wrapper --gradle-version 8.7
##############################################################################

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

APP_HOME=$(cd "$(dirname "$0")" && pwd -P) || exit
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

exec java $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
